### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by nihanthd** [Comcast/go-leaderelection#4]
Hi Team,

My plan is to extend this functionality to be supported with Redis as well as Zookeeper.

In the process I wanted to run `go test ./...`
But it fails with github.comcast.com/viper-cog/clog

Can you update this repo with the required dependencies.

Thanks,
Nihanth Dara

**Comment by youngkin** [comment]
Hi Nihanth,

Apologies for accidentally including `github.comcast.com/viper-cog/clog` as a dependency. As it's only used in `integrationtest/leader_crash_test/mock_worker.go` it can be safely removed. I'll keep this ticket open to do this on master. Until then, If you'd like, you can simply remove/replace all occurrences of clog, including the import, from the file. 

Cheers,
Rich

**Comment by nihanthd** [comment]
@youngkin Thanks for the update.
